name: Validate mim tools metadata
on: [push, pull_request]

jobs:
  validate_metadata:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Validate JSON syntax
      run: |
        jq . tools.json
